---
layout: single
title: Python 예외 처리
categories: Python            
tag:      [blog,Python]
author_profile: true
sidebar:
    nav: "main"

toc: ture
toc_alble: 목록
toc_icon: "bars"
toc_sticky: true
---

### 예외 , 예외 처리 
* 문법적으로 문제가 없는 코드를 실행하는 중에 발생하는 오류 
* 예외처리 : 프로그램을 안전하세 종료 시키기 위해서 예외처리를 한다.

* try 절 안에 예외 발생 가능성이  있는 코드 블록을 배치
* except 절에는 예외가 발생했을댸 처리하는 코드 블록

### try ~ except (기본 형식)
* try 블록안에서 여러종류의 예외가 발생하는 경우에는 except 에 예외형식을 기재 해서 분리해서 처리 가능
* 형식 

```python
try:
# 예외가 발생할 가능성이 있는 코드
except 예외형식1:
# 예외형식1에 해당하는 예외가 발생했을 때 수행될 코드

```

* EX)

```python
try:
      # print('안녕 하세요.')
      # print(10/0)
      n = int(input('정수를 입력 하세요?'))

      if n%2 == 0:
          print('짝수')
      else:
          print('홀수')
except:
      print('예외가 발생 했습니다.')
```

### try ~ except ~ except

```python
try:
# 예외가 발생할 가능성이 있는 코드
except 예외형식1:
# 예외형식1에 해당하는 예외가 발생했을 때 수행될 코드
except 예외형식2:
# 예외형식2에 해당하는 예외가 발생했을 때 수행될 코드
```
* eEX)2

```python
list = [1, 2, 3]

try:
    index = int(input('첨자(index번호)를 입력하세요?'))   # 0, 1, 2
    print(list[index]/0)
except ZeroDivisionError:               # 0 으로 나눌때 예외발생    
    print('0으로 나눌수 없습니다.')
except IndexError:                      # 첨자(index번호)를 잘못 입력 했을때 예외발생
    print('잘못된 첨자 입니다.')
except ValueError:                      # 잘못된 값을 입력 했을때 예외 발생
    print('숫자를 입력 하세요.')

```

* EX)3
* Exception 클래스로 예외를 받으면 다른 except이 무시되어서 사용이 안된다.
* Exception 클래스는 마지막에 사용해야 한다. 

```python

list = [1, 2, 3]

try:
    index = int(input('첨자(index번호)를 입력하세요?'))   # 0, 1, 2
    print(list[index]/0)
except Exception as err:
    print('예외발생:{0}'.format(err))
except ZeroDivisionError as err:               # 0 으로 나눌때 예외발생
    print('0으로 나눌수 없습니다.{0}'.format(err))
except IndexError as err:                      # 첨자(index번호)를 잘못 입력 했을때 예외발생
    print('잘못된 첨자 입니다.{0}'.format(err))
except ValueError as err:                      # 잘못된 값을 입력 했을때 예외 발생
    print('숫자를 입력 하세요.{0}'.format(err))
# except Exception as err:
#     print('예외발생:{0}'.format(err))
```
### try ~ except ~ else

* try에 대한 else가 아니라, except에 대한 else

```python
try:
     예외가 발생할 가능성이 있는 문장
except:
    예외가 발생 했을때 실행될 문장
else:
    except절이 실행되면  실행안됨

    except절이 실행되지 않는 경우에 실행
```

```python
list = [1, 2, 3]

try:
    index = int(input('첨자(index번호)를 입력하세요?'))   # 0, 1, 2
    print('list[{0} : {1}]'.format(index, list[index]))
except Exception as err:
    print('예외발생:{0}'.format(err))
else:
    print('리스트의 요소 출력에 성공 했습니다.')
```
### try ~ except ~ finally 

* (데이터 베이스 연동 할 경우 많이 사용)

```python
try:
    예외가 발생할 가능성이 있는 문장
except:
    예외가 발생 했을때 실행될 문장
finally:
    예외 유무에 상관없이 무조건 실행됨
    파일 닫기, 데이터베이스와 연결을 끊는 내용
```
```python
try:
    print('안녕 하세요.')
    print(param)                    # 예외 발생
except:
    print('예외가 발생 했습니다.')
finally:
    print('무조건 실행')
```
### 예외처리 : try ~ except ~ else ~ finally

```python
try:
    예외가 발생할 가능성이 있는 문자
except:
    예외가 발생 했을때 실행될 문장
else:
    except절이 실행되면 실행안됨
    except절이 실행되지 않는 경우에 실행됨
finally:
    예외 유.무에 상관없이 무조건 실행
    파일 닫기, 데이터베이스와 연결을 끊는 내용
```
```python
list = [1,2,3]

try:
    index = int(input('첨자(인덱스 번호)를 입력하세요?'))    # 0, 1, 2
    print('list[{0} : {1}]'.format(index, list[index]))    
except Exception as err:
    print('예외가 발생했습니다.{0}'.format(err))
else:
    print('리스트의 요소 출력에 성공 했습니다.')
finally:
    print('어떤 일이 있어도 마무리 합니다.')
```
### raise문: 프로그래머가 강제로 예외를 발생

```python

def some_function():
    num = int(input('1~10 사이의 정수를 입력하세요?'))
    if num<1 or num>10:     # 강제로 예외발생 시킴
        raise  Exception('유효하지 않는 숫자입니다.{0}'.format(num))
    else:
        print('입력한 숫자는 {0}입니다.'.format(num))

try:
    some_function()                     # 함수 호출
except Exception as err:
    print('예외가 발생 했습니다.{0}'.format(err))
```

